### PR TITLE
Ci fix

### PR DESCRIPTION
**Pull request by yaalsn**
1. Upgrade actions/checkout version to v2
2. Set jacoco artifact expire time
3. Run pr_test ci when push master to make sure master branch could have a base coverage report

### CODE REVIEW

**Comment by mattisonchao** [comment]
@yaalsn 

We still got 503.

**Comment by Technoboy-** [comment]
Thanks for your help.
We face below issue :
image

**Comment by yaalsn** [comment]
> @yaalsn
> 
> We still got 503.

It seems that github action checkout api just crashed.

**Comment by Technoboy-** [comment]
> > @yaalsn
> > We still got 503.
> 
> It seems that github action checkout api just crashed.

Hi, @yaalsn could I send an email to you and invite you to join the group ?

**Review by mattisonchao — APPROVED** [review]
LGTM +1

**Comment by yaalsn** [comment]
> > > @yaalsn
> > > We still got 503.
> > 
> > 
> > It seems that github action checkout api just crashed.
> 
> Hi, @yaalsn could I send an email to you and invite you to join the group ?

Thanks, my pleasure 😊

**Comment by mattisonchao** [comment]
image

@yaalsn 
We need to fix this problem.

**Review by mattisonchao — CHANGES_REQUESTED** [review]
image

@yaalsn 
We need to fix this problem.

**Comment by yaalsn** [comment]
> image
> 
> @yaalsn We need to fix this problem.

It works now.

**Review by mattisonchao — APPROVED** [review]

**Comment by mattisonchao** [comment]
@Technoboy-  

PTAL :)

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
