### PR TITLE
Merge parallel ci test report (#396)

### PR DESCRIPTION
**Pull request by yaalsn**

### CODE REVIEW

**Review by mattisonchao — APPROVED** [review]
LGTM

**Review by mattisonchao — CHANGES_REQUESTED** [review]
It seems that codacy is stuck.

**Comment by yaalsn** [comment]
> @yaalsn It seems that codacy is stuck.

 🤔️ Emmm...Have you met the same situation?

**Comment by mattisonchao** [comment]
> 

I don't met this situation before. :(
But, wait minute. maybe i can found solution.

**Review by Technoboy- — APPROVED** [review]

**Comment by yaalsn** [comment]
> > 
> 
> I haven't encountered this situation before :( But, wait minute. maybe i can find a solution.

@mattisonchao  PTAL, maybe this discussion will help: https://github.community/t/expected-waiting-for-status-to-be-reported/18001/2

**Pull request merged**
