### PR TITLE
alter unit test config 

### PR DESCRIPTION
**Pull request by JoeCqupt**
#504  ci build fail .

it because  in unit test case the 'properties' field of  MQTTServerConfiguration  is incomplete。 

so i think that  we should create property config to imitate loading real broker config

### CODE REVIEW

**Comment by mattisonchao** [comment]
@Technoboy- @JoeCqupt 
#525  Fix this issue.
So, I think we can close this PR.

**Comment by JoeCqupt** [comment]
“BeanUtils.copyProperties()" can not resolve field which  in MQTTProxyConfiguration but not in MQTTServerConfiguration.

Maybe. take a look at my solution

@mattisonchao @Technoboy-

**Comment by mattisonchao** [comment]
@JoeCqupt  

Yes, you are right. I'm sorry for my wrong understanding.

**Comment by mattisonchao** [comment]
I will check this PR later.

**Review by mattisonchao — APPROVED** [review]

**Comment by Technoboy-** [comment]
Thanks @JoeCqupt

**Pull request merged**
