### PR TITLE
Speed up unit test

### PR DESCRIPTION
**Pull request by yaalsn**
## Motivation
This PR aims to run the tests in parallel to decrease pr_test running time(20min -> 8min)

### CODE REVIEW

**Comment by mattisonchao** [comment]
@yaalsn  

This PR is just to rerun the failed test, is it right ?

**Comment by yaalsn** [comment]
@mattisonchao. 

Not exactly. It seems that `Github Action` can only rerun the whole workflow. This PR aims to run the tests in parallel to decrease `pr_test` running time(20min -> 8min). Cause as the test case's number growing up, the time will increase and timeout will  be offen.   

But this PR bings the problem of code coverage calculating. Every job is test case class and the result should be merged when all the tests runs over.

**Comment by mattisonchao** [comment]
@yaalsn 

I will finish the work related to test recently, we can discuss it.

**Review by mattisonchao — APPROVED** [review]

**Comment by Technoboy-** [comment]
Thanks for your contribution @yaalsn .

**Pull request merged**
