### PR TITLE
Fix MoP http metrics class casting issue.

### LINKED ISSUE #352: A class cast error occured after adding the configuration for additionalServlets.
**Describe the bug**
A class cast error occured after adding the configuration.
```
additionalServlets=mqtt-servlet
additionalServletDirectory=./protocls
```
Error info:
```
Caused by:
java.lang.ClassCastException: class io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler cannot be cast to class io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler (io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler is in unnamed module of loader org.apache.pulsar.common.nar.NarClassLoader @2e674698; io.streamnative.pulsar.handlers.mqtt.MQTTProtocolHandler is in unnamed module of loader org.apache.pulsar.common.nar.NarClassLoader @5f59b6c5)
	at io.streamnative.pulsar.handlers.mqtt.MQTTServiceServlet.getMetricsCollector(MQTTServiceServlet.java:47)
	at io.streamnative.pulsar.handlers.mqtt.MQTTServiceServlet.doGet(MQTTServiceServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:67)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
```

### PR DESCRIPTION
**Pull request by Technoboy-**
Fix #352.

## Motivation
Pulsar will load servlet and protocol handler with different NarClassLoader, and cause the issue.
We should call `MetricsCollector` in protocol handler classloader directly, not casting.

### CODE REVIEW

**Comment by mattisonchao** [comment]
Could we add some test for this PR?

**Comment by mattisonchao** [comment]
@Technoboy-  

We need to cheery-pick this patch to release 2.8.1.

**Review by gaoran10 — APPROVED** [review]

**Comment by Technoboy-** [comment]
> Could we add some test for this PR?

There is a HTTP metrics test before.

**Comment by mattisonchao** [comment]
> > Could we add some test for this PR?
> 
> There is a HTTP metrics test before.

Ok, i see.

**Pull request merged**
